language: python
python: 3.5

branches:
  only:
    - master
    - /version\/\d+\.\d+/

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

before_install:
  - pip install poetry
install:
  - poetry install -v
script:
  - poetry run coverage run unit.py
after_success:
  - poetry run coveralls

before_deploy:
  - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
  - poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    repo: moveaxlab/validation-py
    tags: true
